### ISSUE TITLE
Is it possible to change auto saving interval to a couple of seconds? 

### ISSUE THREAD

**Issue by jedi-ml** [OpenAcousticDevices/AudioMoth-Live#1]
AudioMoth-Live is currently only supports minutes interval. 
is it possible to change this to seconds?

**Comment by pcprince** [comment]
What's your use case for AudioMoth Live that requires shorter automatic recordings? We initially assumed that 1 minute minimum would be sufficient for all users.

**Comment by jedi-ml** [comment]
I am trying to use your application for our AI Project. But actually currently AI model is based on 2 - 4 seconds based WAV files, therefor real time inference of AI engine will require 2 - 4 seconds WAV files.

**Comment by pcprince** [comment]
If you want an easy way to split recordings that short, try using the split function built into the AudioMoth Configuration App, accessible from the "Process" menu.

![image](https://github.com/OpenAcousticDevices/AudioMoth-Live/assets/1685854/1983149a-b2a5-4e03-a1cb-451aaa0776c7)

**Comment by pcprince** [comment]
There's also the option of splitting the files with a script. Which programming languages do you use?
